### ISSUE TITLE
Problem when starting a Minecraft server

### ISSUE THREAD

**Issue by LarrianX** [Fexcraft/FCL#9]
Everything works fine inside the game, but if I try to start just the server, it will throw an error
`[20:30:10] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.3.5 Initialized
[20:30:10] [modloading-worker-0/INFO] [ne.fe.mo.fv.FVTM4/]: MARKER null
[20:30:10] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[20:30:10] [modloading-worker-0/ERROR] [Embeddium/]: Failed to update fingerprint
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at me.jellysquid.mods.sodium.client.data.fingerprint.FingerprintMeasure.create(FingerprintMeasure.java:19) ~[embeddium-0.3.12mc1.20.1.jar%23146!/:?] {re:classloading}
        at me.jellysquid.mods.sodium.client.SodiumClientMod.updateFingerprint(SodiumClientMod.java:100) ~[embeddium-0.3.12mc1.20.1.jar%23146!/:?] {re:classloading}
        at me.jellysquid.mods.sodium.client.SodiumClientMod.<init>(SodiumClientMod.java:41) ~[embeddium-0.3.12mc1.20.1.jar%23146!/:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23173!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[20:30:10] [modloading-worker-0/INFO] [de.ar.ne.fo.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[20:30:11] [Thread-1/WARN] [Supplementaries/]: Failed to fetch contributors data from url https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/master/credits.json, java.lang.RuntimeException: Not a boolean: "true" missed input: {"toffanelly":{"has_globe":"true"}}
[20:30:14] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
Negative index in crash report handler (18/20)
[20:30:15] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID a8e80336-8ccf-4ebd-aa1b-9f99df25290c
[20:30:15] [main/FATAL] [ne.mi.se.lo.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2024-08-01_20.30.15-fml.txt
[20:30:15] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9850fb3f-f44f-4e56-9b7b-3fb24a6c0798
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-08-01 20:30:15
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.5-universal.jar%23176!/:?] {re:classloading}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.5-universal.jar%23176!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23171!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
-- MOD fcl --
Details:
        Mod File: /C:/Games/.Minecraft/ServerSerial1.20.1/mods/fcl-20.5-1.jar
        Failure message: Fexcraft Common Library (fcl) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        Mod Version: 20.5
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {re:mixin}
        at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {re:mixin}
        at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23173!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
        Minecraft Version: 1.20.1
        Minecraft Version ID: 1.20.1
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 17.0.10, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 1834236912 bytes (1749 MiB) / 2621440000 bytes (2500 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 12
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
        Identifier: Intel64 Family 6 Model 62 Stepping 4
        Microarchitecture: Ivy Bridge (Server)
        Frequency (GHz): 2.60
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: USB Mobile Monitor Virtual Display
        Graphics card #0 vendor: Amyuni
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: DriverVersion=2.0.0.1
        Graphics card #1 name: NVIDIA GeForce GTX 1660 SUPER
        Graphics card #1 vendor: NVIDIA (0x10de)
        Graphics card #1 VRAM (MB): 4095.00
        Graphics card #1 deviceId: 0x21c4
        Graphics card #1 versionInfo: DriverVersion=32.0.15.6070
        Memory slot #0 capacity (MB): 8192.00
        Memory slot #0 clockSpeed (GHz): 1.60
        Memory slot #0 type: DDR3
        Memory slot #1 capacity (MB): 8192.00
        Memory slot #1 clockSpeed (GHz): 1.60
        Memory slot #1 type: DDR3
        Virtual memory max (MB): 29108.27
        Virtual memory used (MB): 18069.74
        Swap memory total (MB): 12800.00
        Swap memory used (MB): 2689.51
        JVM Flags: 2 total; -Xms2500M -Xmx4G
        ModLauncher: 10.0.9+10.0.9+main.dcd20f30
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                mixin-0.8.5.jar mixin PLUGINSERVICE
                eventbus-6.0.5.jar eventbus PLUGINSERVICE
                fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE
                fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE
                fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE
                fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE
                accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
                fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE
                modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                javafml@null
        Mod List:
                mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
                moonlight-1.20-2.11.12-forge (1).jar              |Moonlight Library             |moonlight                     |1.20-2.11.12        |COMMON_SET|Manifest: NOSIGNATURE
                AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.9               |COMMON_SET|Manifest: NOSIGNATURE
                signpost-1.20.1-2.02.0.jar                        |signpost                      |signpost                      |2.02.0              |COMMON_SET|Manifest: NOSIGNATURE
                Female-Gender-Mod-forge-1.20.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.20.1-3.0.1        |COMMON_SET|Manifest: NOSIGNATURE
                mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
                amendments-1.20-1.1.18.jar                        |Amendments                    |amendments                    |1.20-1.1.18         |COMMON_SET|Manifest: NOSIGNATURE
                ShoulderSurfing-Forge-1.20.1-2.9.5.jar            |Shoulder Surfing              |shouldersurfing               |1.20.1-2.9.5        |COMMON_SET|Manifest: NOSIGNATURE
                CMDCam_FORGE_v2.1.1_mc1.20.1.jar                  |CMDCam                        |cmdcam                        |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
                player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |COMMON_SET|Manifest: NOSIGNATURE
                CreativeCore_FORGE_v2.11.25_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.25             |COMMON_SET|Manifest: NOSIGNATURE
                fcl-20.5-1.jar                                    |Fexcraft Common Library       |fcl                           |20.5                |ERROR     |Manifest: NOSIGNATURE
                firstperson-forge-2.3.4-mc1.20.1.jar              |FirstPerson                   |firstperson                   |2.3.4               |COMMON_SET|Manifest: NOSIGNATURE
                Paintings-forge-1.20.1-11.0.0.0.jar               |Paintings ++                  |paintings                     |11.0.0.0            |COMMON_SET|Manifest: NOSIGNATURE
                server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
                ForgeEndertech-1.20.1-11.1.1.1-build.0365.jar     |ForgeEndertech                |forgeendertech                |11.1.1.1            |COMMON_SET|Manifest: NOSIGNATURE
                Fallingleaves-1.20.1-2.1.0.jar                    |Falling Leaves                |fallingleaves                 |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
                journeymap-1.20.1-5.9.20-forge.jar                |Journeymap                    |journeymap                    |5.9.20              |COMMON_SET|Manifest: NOSIGNATURE
                mixinextras-forge-0.2.1-beta.2.jar                |MixinExtras                   |mixinextras                   |0.2.1-beta.2        |COMMON_SET|Manifest: NOSIGNATURE
                WorldEditCUI-1.20+01.jar                          |WorldEditCUI                  |worldeditcui                  |1.20+01             |COMMON_SET|Manifest: NOSIGNATURE
                worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |COMMON_SET|Manifest: NOSIGNATURE
                coroutil-forge-1.20.1-1.3.7.jar                   |CoroUtil                      |coroutil                      |1.20.1-1.3.7        |COMMON_SET|Manifest: NOSIGNATURE
                WorldHandler-1.20.1-3.5.jar                       |World Handler                 |worldhandler                  |1.20.1-3.5          |COMMON_SET|Manifest: NOSIGNATURE
                constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |COMMON_SET|Manifest: NOSIGNATURE
                mcw-doors-1.1.1forge-mc1.20.1.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
                cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
                automobility-0.4.2-1.20.1-forge.jar               |Automobility                  |automobility                  |0.4.2+1.20.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
                architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
                ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar              |ItemPhysic                    |itemphysic                    |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
                BetterF3-7.0.2-Forge-1.20.1.jar                   |BetterF3                      |betterf3                      |7.0.2               |COMMON_SET|Manifest: NOSIGNATURE
                nfm-2024.05.11-1.20.1.jar                         |Nosiphus Furniture Mod        |nfm                           |2024.05.11          |COMMON_SET|Manifest: NOSIGNATURE
                skinlayers3d-forge-1.6.2-mc1.20.1.jar             |3d-Skin-Layers                |skinlayers3d                  |1.6.2               |COMMON_SET|Manifest: NOSIGNATURE
                cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                MOAdecor-BATH-1.20.1.jar                          |MOA DECOR: BATH               |moa_decor_bath                |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
                supplementaries-1.20-2.8.10.jar                   |Supplementaries               |supplementaries               |1.20-2.8.10         |COMMON_SET|Manifest: NOSIGNATURE
                fvtm-4.20.5.jar                                   |Fex's Vehicle & Transportation|fvtm                          |4.20.5              |COMMON_SET|Manifest: NOSIGNATURE
                embeddium-0.3.12mc1.20.1.jar                      |Embeddium                     |embeddium                     |0.3.12+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
                LittleTiles_BETA_v1.6.0-pre100_mc1.20.1.jar       |LittleTiles                   |littletiles                   |1.6.0-pre100        |COMMON_SET|Manifest: NOSIGNATURE
        Crash Report UUID: 9850fb3f-f44f-4e56-9b7b-3fb24a6c0798
        FML: 47.3
        Forge: net.minecraftforge:47.3.5[20:30:15] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Fexcraft Common Library (fcl) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23172!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.5-universal.jar%23176!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23171!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}`

**Comment by Fexcraft** [comment]
Client side class was called on server side.
Will look into it.
